export const Vintage = [
  {
    id: 1,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/홀로그램.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 2,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/홀로그램2.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 3,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/고양이.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 4,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/앵무새.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 5,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/스프레이.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 6,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/보라나비.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 7,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/물.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 9,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/거품.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 10,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/bf1.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 11,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/ticket.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 12,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/tape.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 13,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/cocacola.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 14,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/camera.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 15,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/books.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 16,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/flower.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 17,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/flower2.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 18,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/flower3.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 19,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/flower4.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 20,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/flower5.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 21,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/flower6.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 22,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/flower7.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 23,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/flower8.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 24,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/flower9.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 25,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/flower10.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 26,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/flower11.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 27,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/angel.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 28,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/angel2.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 29,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/christmas1.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 30,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/리스.png`,
    spec: '',
    class: 'vintage',
  },
  {
    id: 31,
    fileUrl: `${process.env.PUBLIC_URL}/images/stickers/vintage/pine.png`,
    spec: '',
    class: 'vintage',
  },
];
  