const MyDesigns = [
  {
    artistName: '뉴진스',
    designs:
      [
        { 
          id: 1,
          ent: 'ADOR',
          artist: '뉴진스',
          member: '하니',
          collection: 'Get Up(The 2nd EP)',
          title: '하니V1',
          date: '2023. 10. 10',
          time: '오후 3시 32분',
          fileUrl: `${process.env.PUBLIC_URL}/images/design/하니V1.jpeg`,
        },
        {
          id: 2,
          ent: 'ADOR',
          artist: '뉴진스',
          member: '다니엘',
          collection: 'Get Up(The 2nd EP)',
          title: "하니V2",
          date: '2023. 08. 10',
          time: '오후 3시 32분',
          fileUrl: `${process.env.PUBLIC_URL}/images/design/다니엘V1.jpeg`,
        },
        { 
          id: 3,
          ent: 'ADOR',
          artist: '뉴진스',
          member: '해린',
          collection: 'Get Up(The 2nd EP)',
          title: '하니V1',
          date: '2023. 10. 10',
          time: '오후 3시 32분',
          fileUrl: `${process.env.PUBLIC_URL}/images/design/해린V1.jpeg`,
        },
        {
          id: 4,
          ent: 'ADOR',
          artist: '뉴진스',
          member: '하니',
          collection: 'Get Up(The 2nd EP)',
          title: "하니V2",
          date: '2023. 08. 10',
          time: '오후 3시 32분',
          fileUrl: `${process.env.PUBLIC_URL}/images/design/empty.png`,
        },
        { 
          id: 5,
          ent: 'ADOR',
          artist: '뉴진스',
          member: '하니',
          collection: 'Get Up(The 2nd EP)',
          title: '하니V1',
          date: '2023. 10. 10',
          time: '오후 3시 32분',
          fileUrl: `${process.env.PUBLIC_URL}/images/design/empty.png`,
        },
        {
          id: 6,
          ent: 'ADOR',
          artist: '뉴진스',
          member: '하니',
          collection: 'OMG',
          title: "하니V2",
          date: '2023. 08. 10',
          time: '오후 3시 32분',
          fileUrl: `${process.env.PUBLIC_URL}/images/design/혜인V2.jpeg`,
        },
      ],
  },
  {
    artistName: '방탄소년단',
    designs:
      [
        {
          id: 1,
          ent: 'BIGHIT',
          artist: '방탄소년단',
          member: '정국',
          collection: 'Butter',
          title: '정국V1',
          date: '2023. 11. 05',
          time: '오전 10시 13분',
          fileUrl: `${process.env.PUBLIC_URL}/images/design/정국V1.jpeg`,
        },
        {
          id: 2,
          ent: 'BIGHIT',
          artist: '방탄소년단',
          member: '정국',
          collection: 'Butter',
          title: '정국V2',
          date: '2023. 10. 12',
          time: '오전 10시 13분',
          fileUrl: `${process.env.PUBLIC_URL}/images/design/정국V1.jpeg`,
        },
        {
          id: 3,
          ent: 'BIGHIT',
          artist: '방탄소년단',
          member: '정국',
          collection: 'Butter',
          title: '정국V2',
          date: '2023. 09. 05',
          time: '오전 10시 13분',
          fileUrl: `${process.env.PUBLIC_URL}/images/design/정국V1.jpeg`,
        },
        {
          id: 4,
          ent: 'BIGHIT',
          artist: '방탄소년단',
          member: '정국',
          collection: 'Butter',
          title: '정국V2',
          date: '2023. 08. 05',
          time: '오전 10시 13분',
          fileUrl: `${process.env.PUBLIC_URL}/images/design/empty.png`,
        },
      ],
  },
  {
    artistName: '아이유',
    designs:
      [
        {
          id: 1,
          ent: 'EDAM',
          artist: '아이유',
          collection: 'Lilac',
          title: '',
          date: '',
          time: '',
          fileUrl: `${process.env.PUBLIC_URL}/images/design/.jpeg`,
        },
        {
          id: 2,
          ent: 'EDAM',
          artist: '아이유',
          collection: 'Lilac',
          title: '',
          date: '',
          time: '',
          fileUrl: `${process.env.PUBLIC_URL}/images/design/.jpeg`,
        },
      ],
  },
  {
    artistName: '에스파',
    designs:
      [
        {
          id: 1,
          ent: 'SM',
          artist: '에스파',
          member: '카리나',
          collection: 'My World',
          title: '',
          date: '2023. 09. 20',
          time: '오후 2시 10분',
          fileUrl: `${process.env.PUBLIC_URL}/images/design/카리나V1.jpeg`,
        },
        {
          id: 2,
          ent: 'SM',
          artist: '에스파',
          member: '카리나',
          collection: 'My World',
          title: '',
          date: '2023. 09. 22',
          time: '오후 6시 7분',
          fileUrl: `${process.env.PUBLIC_URL}/images/design/카리나V1.jpeg`,
        },
      ],
  },



]

export default MyDesigns;